### ISSUE TITLE
GitHub-Visual bağlantını tam yapamamışsın

### ISSUE THREAD

**Issue by OzgurKucet** [ruveyharuzgar/ReCapProject#1]
GitHub hesabına bağlama işini visual Studio dan iyi yapamamışsın. Onu düzeltmeye çalış yada dc den yardım al bence.
https://www.youtube.com/watch?v=Y1fBfrcRMEs&list=LL&index=6&t=514s
izlersen bir sıkıntı kalacağını sanmıyorum ama yine de yapamazsan yardım ederim.

**Comment by ruveyharuzgar** [comment]
Merhabalar herhangi bir hata görmüyorum, nereden böyle bir sonuca vardınız?

**Comment by OzgurKucet** [comment]
Kodlar ile birlikte dll dosyaları da var debug dosyalarınız falan da gelmiş visual studio yardımıyla kodlarınızı yüklerseniz debug dosyalarını yüklemiyor. Mesela build sonucu dosyalarınız burada görünmüyor olması lazım.

**Comment by ruveyharuzgar** [comment]
Evet doğru çok teşekkürler.

**Comment by OzgurKucet** [comment]
Rica ederim kolay gelsin.
